version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/platform-browser"
    versions:
    - 11.0.5
    - 11.1.1
    - 11.2.3
    - 11.2.8
  - dependency-name: "@angular/compiler"
    versions:
    - 11.2.3
    - 8.2.14
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.0.5
    - 11.1.1
    - 11.2.3
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.5
    - 11.1.2
    - 11.2.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@angular/language-service"
    versions:
    - 11.0.5
    - 11.1.1
    - 11.2.3
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
  - dependency-name: "@angular/core"
    versions:
    - 8.2.14
  registries:
  - npm-registry-registry-npmjs-org
